sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Y9RT2/j1npMHb40WbpaXaxko85n2ZTnY+VBIpaIrIDfEw7W6yAInIymS750AYDnUbaD6+9u+72NcwDwnlonmg8sQc+2NSc3KY9b+3wdaLkiN2Zvr13ImWCp5PDEGds7YYKd0RbRKmpkzaxhBWmjEK83ziBwwFzrWtTOxATQtBsPUeSi/eDP+Y5w8TJEbkO4w98yk+avzS63FdyvfFuyESynZXGEu4+Somt6m2yu5bLFqWC2beOid/2whW73wVxWBPm2CA2Y1iiPC4cB3z/7DWIWP7u9ebX+rscfEcV7MOo6wSwA+1lHg8Jgl+qnmloQl90/I3Gf7+lLXEFgY1E+C+zVk4tmP0JXe81hJCxOMfaWX8+4t8fDyoVP3W1PiIaqKS1lF4CbGftzu5c3FpepkQCTxiRrqYtP7s4xIcja3ZRXQtrnnuqG83iP+SkWFJSLCaM00jRY4eBD7bqS7K+FlBXJfnNp/UPJovPuHtKhv6rhd0OSDy6HfIiWuwKOYt8yqregT8ZdIJmmDcUBMnqmxsKao/iaI1kZpalMhOy+ynUofmnEgr9xVp17xJk9K1zXPbj1Tir/iRkz8ilnMnU2O5AHX4KuiFKX6hmuDul+lcarh2xUXthYlqy4oxkYbDAL9q7ytml2z/FLYEmYRZR2lU0ZWyu82ovZB9lysGbJwWKk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Concerning-Christian-Liberty--with-Letter-of-Martin-Luther-to-Pope-Leo-X._1911
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy